pollutants:
  - PM2.5
  - PM10
  - NO2
  - SO2
  - CO
  - O3

time_settings:
  frequency: 'H'  # Hourly
  fill_method: 'interpolate'
  
train_test_split:
  test_size: 0.2
  validation_size: 0.1

feature_engineering:
  lag_features: [1, 3, 6, 12, 24]
  rolling_windows: [3, 6, 12, 24]
  time_features:
    - hour
    - day_of_week
    - month
    - season